name: Deploy WordPress Theme to StackCP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: Add host key to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ssh.gb.stackcp.com >> ~/.ssh/known_hosts
          
      - name: Deploy theme to WordPress
        run: |
          # Replace "squarebook-main" with your actual theme directory name
          rsync -avz --exclude='.git' \
                     --exclude='.github' \
                     --exclude='node_modules' \
                     --exclude='.gitignore' \
                     --exclude='README.md' \
                     --exclude='.DS_Store' \
                     . squarebook.com@ssh.gb.stackcp.com:~/public_html/wp-content/themes/your-theme-name